/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.madhouse.dsp.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WinNotice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1169637257332935318L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WinNotice\",\"namespace\":\"com.madhouse.dsp.avro\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"bidid\",\"type\":\"string\"},{\"name\":\"mediaid\",\"type\":\"long\"},{\"name\":\"adspaceid\",\"type\":\"long\"},{\"name\":\"projectid\",\"type\":\"long\"},{\"name\":\"cid\",\"type\":\"long\"},{\"name\":\"crid\",\"type\":\"long\"},{\"name\":\"price\",\"type\":\"int\"},{\"name\":\"location\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WinNotice> ENCODER =
      new BinaryMessageEncoder<WinNotice>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WinNotice> DECODER =
      new BinaryMessageDecoder<WinNotice>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<WinNotice> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<WinNotice> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WinNotice>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this WinNotice to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a WinNotice from a ByteBuffer. */
  public static WinNotice fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long time;
  @Deprecated public int status;
  @Deprecated public CharSequence bidid;
  @Deprecated public long mediaid;
  @Deprecated public long adspaceid;
  @Deprecated public long projectid;
  @Deprecated public long cid;
  @Deprecated public long crid;
  @Deprecated public int price;
  @Deprecated public CharSequence location;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WinNotice() {}

  /**
   * All-args constructor.
   * @param time The new value for time
   * @param status The new value for status
   * @param bidid The new value for bidid
   * @param mediaid The new value for mediaid
   * @param adspaceid The new value for adspaceid
   * @param projectid The new value for projectid
   * @param cid The new value for cid
   * @param crid The new value for crid
   * @param price The new value for price
   * @param location The new value for location
   */
  public WinNotice(Long time, Integer status, CharSequence bidid, Long mediaid, Long adspaceid, Long projectid, Long cid, Long crid, Integer price, CharSequence location) {
    this.time = time;
    this.status = status;
    this.bidid = bidid;
    this.mediaid = mediaid;
    this.adspaceid = adspaceid;
    this.projectid = projectid;
    this.cid = cid;
    this.crid = crid;
    this.price = price;
    this.location = location;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return status;
    case 2: return bidid;
    case 3: return mediaid;
    case 4: return adspaceid;
    case 5: return projectid;
    case 6: return cid;
    case 7: return crid;
    case 8: return price;
    case 9: return location;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: time = (Long)value$; break;
    case 1: status = (Integer)value$; break;
    case 2: bidid = (CharSequence)value$; break;
    case 3: mediaid = (Long)value$; break;
    case 4: adspaceid = (Long)value$; break;
    case 5: projectid = (Long)value$; break;
    case 6: cid = (Long)value$; break;
    case 7: crid = (Long)value$; break;
    case 8: price = (Integer)value$; break;
    case 9: location = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(Long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(Integer value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'bidid' field.
   * @return The value of the 'bidid' field.
   */
  public CharSequence getBidid() {
    return bidid;
  }

  /**
   * Sets the value of the 'bidid' field.
   * @param value the value to set.
   */
  public void setBidid(CharSequence value) {
    this.bidid = value;
  }

  /**
   * Gets the value of the 'mediaid' field.
   * @return The value of the 'mediaid' field.
   */
  public Long getMediaid() {
    return mediaid;
  }

  /**
   * Sets the value of the 'mediaid' field.
   * @param value the value to set.
   */
  public void setMediaid(Long value) {
    this.mediaid = value;
  }

  /**
   * Gets the value of the 'adspaceid' field.
   * @return The value of the 'adspaceid' field.
   */
  public Long getAdspaceid() {
    return adspaceid;
  }

  /**
   * Sets the value of the 'adspaceid' field.
   * @param value the value to set.
   */
  public void setAdspaceid(Long value) {
    this.adspaceid = value;
  }

  /**
   * Gets the value of the 'projectid' field.
   * @return The value of the 'projectid' field.
   */
  public Long getProjectid() {
    return projectid;
  }

  /**
   * Sets the value of the 'projectid' field.
   * @param value the value to set.
   */
  public void setProjectid(Long value) {
    this.projectid = value;
  }

  /**
   * Gets the value of the 'cid' field.
   * @return The value of the 'cid' field.
   */
  public Long getCid() {
    return cid;
  }

  /**
   * Sets the value of the 'cid' field.
   * @param value the value to set.
   */
  public void setCid(Long value) {
    this.cid = value;
  }

  /**
   * Gets the value of the 'crid' field.
   * @return The value of the 'crid' field.
   */
  public Long getCrid() {
    return crid;
  }

  /**
   * Sets the value of the 'crid' field.
   * @param value the value to set.
   */
  public void setCrid(Long value) {
    this.crid = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public Integer getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(Integer value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public CharSequence getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(CharSequence value) {
    this.location = value;
  }

  /**
   * Creates a new WinNotice RecordBuilder.
   * @return A new WinNotice RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new WinNotice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WinNotice RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new WinNotice RecordBuilder by copying an existing WinNotice instance.
   * @param other The existing instance to copy.
   * @return A new WinNotice RecordBuilder
   */
  public static Builder newBuilder(WinNotice other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for WinNotice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WinNotice>
    implements org.apache.avro.data.RecordBuilder<WinNotice> {

    private long time;
    private int status;
    private CharSequence bidid;
    private long mediaid;
    private long adspaceid;
    private long projectid;
    private long cid;
    private long crid;
    private int price;
    private CharSequence location;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bidid)) {
        this.bidid = data().deepCopy(fields()[2].schema(), other.bidid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mediaid)) {
        this.mediaid = data().deepCopy(fields()[3].schema(), other.mediaid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.adspaceid)) {
        this.adspaceid = data().deepCopy(fields()[4].schema(), other.adspaceid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.projectid)) {
        this.projectid = data().deepCopy(fields()[5].schema(), other.projectid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cid)) {
        this.cid = data().deepCopy(fields()[6].schema(), other.cid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.crid)) {
        this.crid = data().deepCopy(fields()[7].schema(), other.crid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.price)) {
        this.price = data().deepCopy(fields()[8].schema(), other.price);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location)) {
        this.location = data().deepCopy(fields()[9].schema(), other.location);
        fieldSetFlags()[9] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing WinNotice instance
     * @param other The existing instance to copy.
     */
    private Builder(WinNotice other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bidid)) {
        this.bidid = data().deepCopy(fields()[2].schema(), other.bidid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mediaid)) {
        this.mediaid = data().deepCopy(fields()[3].schema(), other.mediaid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.adspaceid)) {
        this.adspaceid = data().deepCopy(fields()[4].schema(), other.adspaceid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.projectid)) {
        this.projectid = data().deepCopy(fields()[5].schema(), other.projectid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cid)) {
        this.cid = data().deepCopy(fields()[6].schema(), other.cid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.crid)) {
        this.crid = data().deepCopy(fields()[7].schema(), other.crid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.price)) {
        this.price = data().deepCopy(fields()[8].schema(), other.price);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location)) {
        this.location = data().deepCopy(fields()[9].schema(), other.location);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public Long getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public Builder setTime(long value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public Integer getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public Builder setStatus(int value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public Builder clearStatus() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bidid' field.
      * @return The value.
      */
    public CharSequence getBidid() {
      return bidid;
    }

    /**
      * Sets the value of the 'bidid' field.
      * @param value The value of 'bidid'.
      * @return This builder.
      */
    public Builder setBidid(CharSequence value) {
      validate(fields()[2], value);
      this.bidid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bidid' field has been set.
      * @return True if the 'bidid' field has been set, false otherwise.
      */
    public boolean hasBidid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bidid' field.
      * @return This builder.
      */
    public Builder clearBidid() {
      bidid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'mediaid' field.
      * @return The value.
      */
    public Long getMediaid() {
      return mediaid;
    }

    /**
      * Sets the value of the 'mediaid' field.
      * @param value The value of 'mediaid'.
      * @return This builder.
      */
    public Builder setMediaid(long value) {
      validate(fields()[3], value);
      this.mediaid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'mediaid' field has been set.
      * @return True if the 'mediaid' field has been set, false otherwise.
      */
    public boolean hasMediaid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'mediaid' field.
      * @return This builder.
      */
    public Builder clearMediaid() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'adspaceid' field.
      * @return The value.
      */
    public Long getAdspaceid() {
      return adspaceid;
    }

    /**
      * Sets the value of the 'adspaceid' field.
      * @param value The value of 'adspaceid'.
      * @return This builder.
      */
    public Builder setAdspaceid(long value) {
      validate(fields()[4], value);
      this.adspaceid = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'adspaceid' field has been set.
      * @return True if the 'adspaceid' field has been set, false otherwise.
      */
    public boolean hasAdspaceid() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'adspaceid' field.
      * @return This builder.
      */
    public Builder clearAdspaceid() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'projectid' field.
      * @return The value.
      */
    public Long getProjectid() {
      return projectid;
    }

    /**
      * Sets the value of the 'projectid' field.
      * @param value The value of 'projectid'.
      * @return This builder.
      */
    public Builder setProjectid(long value) {
      validate(fields()[5], value);
      this.projectid = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'projectid' field has been set.
      * @return True if the 'projectid' field has been set, false otherwise.
      */
    public boolean hasProjectid() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'projectid' field.
      * @return This builder.
      */
    public Builder clearProjectid() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'cid' field.
      * @return The value.
      */
    public Long getCid() {
      return cid;
    }

    /**
      * Sets the value of the 'cid' field.
      * @param value The value of 'cid'.
      * @return This builder.
      */
    public Builder setCid(long value) {
      validate(fields()[6], value);
      this.cid = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'cid' field has been set.
      * @return True if the 'cid' field has been set, false otherwise.
      */
    public boolean hasCid() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'cid' field.
      * @return This builder.
      */
    public Builder clearCid() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'crid' field.
      * @return The value.
      */
    public Long getCrid() {
      return crid;
    }

    /**
      * Sets the value of the 'crid' field.
      * @param value The value of 'crid'.
      * @return This builder.
      */
    public Builder setCrid(long value) {
      validate(fields()[7], value);
      this.crid = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'crid' field has been set.
      * @return True if the 'crid' field has been set, false otherwise.
      */
    public boolean hasCrid() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'crid' field.
      * @return This builder.
      */
    public Builder clearCrid() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public Integer getPrice() {
      return price;
    }

    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public Builder setPrice(int value) {
      validate(fields()[8], value);
      this.price = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public Builder clearPrice() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public CharSequence getLocation() {
      return location;
    }

    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public Builder setLocation(CharSequence value) {
      validate(fields()[9], value);
      this.location = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public Builder clearLocation() {
      location = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WinNotice build() {
      try {
        WinNotice record = new WinNotice();
        record.time = fieldSetFlags()[0] ? this.time : (Long) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (Integer) defaultValue(fields()[1]);
        record.bidid = fieldSetFlags()[2] ? this.bidid : (CharSequence) defaultValue(fields()[2]);
        record.mediaid = fieldSetFlags()[3] ? this.mediaid : (Long) defaultValue(fields()[3]);
        record.adspaceid = fieldSetFlags()[4] ? this.adspaceid : (Long) defaultValue(fields()[4]);
        record.projectid = fieldSetFlags()[5] ? this.projectid : (Long) defaultValue(fields()[5]);
        record.cid = fieldSetFlags()[6] ? this.cid : (Long) defaultValue(fields()[6]);
        record.crid = fieldSetFlags()[7] ? this.crid : (Long) defaultValue(fields()[7]);
        record.price = fieldSetFlags()[8] ? this.price : (Integer) defaultValue(fields()[8]);
        record.location = fieldSetFlags()[9] ? this.location : (CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WinNotice>
    WRITER$ = (org.apache.avro.io.DatumWriter<WinNotice>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WinNotice>
    READER$ = (org.apache.avro.io.DatumReader<WinNotice>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
